Only use actual branch names when verifying branch
pyenv/pyenv-update pull request #4
Opened 2018-03-01 08:11 UTC by wjv

When pyenv-update verifies the current branch name using `git name-rev`, it fails to exclude refs that are not (branch) heads. So if there is, for instance, a version tag present, pyenv-update will detect that and assume that the checked-out version is not on branch `master`, even though it is.

For instance, right now (as I write this), the `v1.2.2` tag is triggering this issue:

    $ pyenv update
    Updating /Users/visagie/.pyenv...
    pyenv-update: /Users/visagie/.pyenv is not on master branch.
    Updating /Users/visagie/.pyenv/plugins/pyenv-alias...
    From https://github.com/s1341/pyenv-alias
     * branch            master     -> FETCH_HEAD
    Already up to date.
    …  [etc.]

2018-03-02 17:14 UTC, mikicz commented
I was just about to report this bug, excellent, thanks for the fix, now it just has to be merged and released :)

2018-03-02 22:01 UTC, yyuu requested changes
CI's failing. Update tests to pass it

2018-03-03 21:16 UTC, mikicz commented
If I may, tests aren't failing, there are no tests in this repository. Actually, `.travis.yml` isn't even present in the repo. Travis is turned on for this repository, but it's failing because there isn't a configuration on what to run.

2018-03-04 16:04 UTC, merged

2018-03-04 19:25 UTC, wjv commented
Thanks! :)

2018-03-05 00:39 UTC, yyuu commented
Ah, you're right. It looks like somehow I turned travis-ci on regardless of absence of test. I'll disable it later. Anyway thanks for PR.

2018-03-13 14:48 UTC, joshsleeper commented
@pjhinton @joshfriend @wjv 
I can't seem to reply to the thread above as I'm not a member/contributor, but I'm also using `git 1.8.3.1` on CentOS 7.4 so that's likely my issue.

@wjv the `--exclude` option doesn't seem to exist until pretty recent versions of `git`, assuming this commit date is correct: https://github.com/git/git/commit/96415b49dc4e10b64c014516a3f7cd9a51ed5269

If nothing else, it definitely doesn't exist in `git 1.8.3.1` for us to test with. ;)

That said, I did confirm that simply _removing_ the `--refs` options (see below) returns the correct branch name as expected.

    git name-rev --name-only HEAD